### ISSUE TITLE
readme incorrect

### ISSUE THREAD

**Issue by slaughtr** [cloudposse/terraform-aws-documentdb-cluster#2]
Forgive me for opening an issue, but it seems like you use some doc generation tool and I'm not sure what all would need to be touched to update the readme.

`admin_user` and `admin_password` are listed in the docs, but the module uses `master_username` and `master_password`. Small thing and simple fix :)

**Comment by aknysh** [comment]
thanks @slaughtr 

we'll update it, or if you can open a PR, please rebuild README by executing these commands:

```
make init
make readme/deps
make readme
```

It will add the new variables and outputs to `README.md` automatically.

In general, any changes to README should be made in `README.yaml, and after that executing the commands above will rebuild `README.yaml` into `README.md` and add all new variables and outputs to `README.md`

thanks

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-documentdb-cluster/pull/3
