### ISSUE TITLE
Issue with count for allowed_security_groups

### ISSUE THREAD

**Issue by slaughtr** [cloudposse/terraform-aws-documentdb-cluster#4]
Hello again, I'm back. I've run into an issue with `allowed_security_groups`, which I assume would also affect `allowed_cidr_blocks`

The issue is related to passing list variables around, as seen here: https://github.com/hashicorp/terraform/issues/13103

As I've been tying the pieces of a large stack together, I finally had my bastion host all set up and attempted to add the SG to the `allowed_security_groups` declaration:

```hcl
allowed_security_groups = ["${module.bastion.bastion_host_security_group}"]
```

Which gives me this error:
```shell
* module.documentdb_cluster.aws_security_group_rule.ingress_security_groups: aws_security_group_rule.ingress_security_groups: value of 'count' cannot be computed
```

This seems to be because the `length(var.allowed_security_groups)` is not seeing a list, due to aforementioned TF bug with list variables. From what I can tell it's that TF doesn't know what to do with "dynamic" length lists. I think y'all even have a writeup on it....[here](https://docs.cloudposse.com/troubleshooting/terraform-value-of-count-cannot-be-computed/)

I tried several things, as you can see in [this godawful commit history](https://github.com/slaughtr/terraform-aws-documentdb-cluster/commits/master). I landed on just using an `allowed_security_groups_count` variable, which isn't ideal but did allow me to finally create the stack. I was hoping y'all had some further expertise that might lead to a better solution, and if not I can modify my solution to better match your current config and open a PR.

Thanks again for making this!

**Comment by aknysh** [comment]
closing as outdated.
please try https://github.com/cloudposse/terraform-aws-documentdb-cluster/releases/tag/0.11.0
