### ISSUE TITLE
random password resource still generated even if module is disabled

### ISSUE THREAD

**Issue by MatanHeledPort** [cloudposse/terraform-aws-documentdb-cluster#65]
### Describe the Bug

Hi.
I encountered a bug where the random_password resource is still generated even if the module was disabled

I opened a PR for a fix and would appreciate an approval:
https://github.com/cloudposse/terraform-aws-documentdb-cluster/pull/64

### Expected Behavior

Password to not generate if module is disabled

### Steps to Reproduce

set var.enabled to false

**Comment by milldr** [comment]
resolved by #44
