### ISSUE TITLE
Argument "storage_type" for aws_docdb_cluster is not expected with AWS provider < 5.29.0, Module Version 0.25.0

### ISSUE THREAD

**Issue by abeleon-m1** [cloudposse/terraform-aws-documentdb-cluster#86]
### Describe the Bug

Module version 0.25.0 allows for "storage_type" variable for `aws_docdb_cluster`. This is not supported by lower AWS providers. Version 5.29.0 required for this. https://registry.terraform.io/providers/hashicorp/aws/5.29.0/docs/resources/docdb_cluster

Fix requirements: https://github.com/cloudposse/terraform-aws-documentdb-cluster/blob/main/versions.tf#L7 or make optional.

```
Validation failed: modules/main
╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/documentdb_cluster/main.tf line 72, in resource "aws_docdb_cluster" "default":
│   72:   storage_type                    = var.storage_type
│ 
│ An argument named "storage_type" is not expected here.
```

### Expected Behavior

Allows for plan with lower AWS versions error

### Steps to Reproduce

Pin an AWS version lower than 5.29.0 and attempt to plan with latest module (0.25.0).

**Comment by danieldrey** [comment]
So I can't use the storage_type parameter with a provider lower than 5.29?
